name: Deployment
on:
  push:
    branches:
      - dev
env:
  auth_token: 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

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: yarn install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "rich.sugiarto@gmail.com"
        git config --global user.name "richardsugiarto"
        git remote set-url origin https://${{env.auth_token}}@github.com/richardsugiarto/portofolio.git
        npm run deploy
